# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Sedat\Desktop\Programlarım\Hece Oluşturma\ana_ekran.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1920, 1080)
        Form.setMinimumSize(QtCore.QSize(1920, 1080))
        Form.setMaximumSize(QtCore.QSize(1920, 1080))
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.label.setMinimumSize(QtCore.QSize(1920, 1080))
        self.label.setMaximumSize(QtCore.QSize(1920, 1080))
        self.label.setStyleSheet("background-image: url(:/newPrefix/duplo4.jpg);\n"
"image: url(:/newPrefix/arkaplan(1).png);")
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(1650, 140, 231, 61))
        self.pushButton.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"    background-image: url(:/newPrefix/1_normal.png);\n"
"background-repeat: no-repeat;\n"
"background-color: transparent;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-image: url(:/newPrefix/1_hover.png);\n"
"background-repeat: no-repeat;\n"
"background-color: transparent;\n"
"\n"
"}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(1650, 210, 231, 61))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"    background-image: url(:/newPrefix/2_normal.png);\n"
"background-repeat: no-repeat;\n"
"background-color: transparent;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-image: url(:/newPrefix/2_hover.png);\n"
"background-repeat: no-repeat;\n"
"background-color: transparent;\n"
"\n"
"}")
        self.pushButton_2.setText("")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setGeometry(QtCore.QRect(1650, 280, 231, 61))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"    background-image: url(:/newPrefix/3_normal.png);\n"
"background-repeat: no-repeat;\n"
"background-color: transparent;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-image: url(:/newPrefix/3_hover.png);\n"
"background-repeat: no-repeat;\n"
"background-color: transparent;\n"
"\n"
"}")
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setGeometry(QtCore.QRect(1650, 350, 231, 61))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"    background-image: url(:/newPrefix/4_normal.png);\n"
"background-repeat: no-repeat;\n"
"background-color: transparent;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-image: url(:/newPrefix/4_hover.png);\n"
"background-repeat: no-repeat;\n"
"background-color: transparent;\n"
"\n"
"}")
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Form)
        self.pushButton_5.setGeometry(QtCore.QRect(1650, 420, 231, 61))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"    background-image: url(:/newPrefix/5_normal.png);\n"
"background-repeat: no-repeat;\n"
"background-color: transparent;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-image: url(:/newPrefix/5_hover.png);\n"
"background-repeat: no-repeat;\n"
"background-color: transparent;\n"
"\n"
"}")
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(-100, 420, 500, 400))
        self.label_2.setMinimumSize(QtCore.QSize(320, 220))
        self.label_2.setMaximumSize(QtCore.QSize(500, 400))
        self.label_2.setStyleSheet("background-image: url(:/newPrefix/bulut.png);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(160, 730, 500, 400))
        self.label_3.setMinimumSize(QtCore.QSize(320, 220))
        self.label_3.setMaximumSize(QtCore.QSize(500, 400))
        self.label_3.setStyleSheet("background-image: url(:/newPrefix/bulut.png);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(650, 740, 500, 400))
        self.label_4.setMinimumSize(QtCore.QSize(320, 220))
        self.label_4.setMaximumSize(QtCore.QSize(500, 400))
        self.label_4.setStyleSheet("background-image: url(:/newPrefix/bulut.png);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(1120, 720, 500, 400))
        self.label_5.setMinimumSize(QtCore.QSize(320, 220))
        self.label_5.setMaximumSize(QtCore.QSize(500, 400))
        self.label_5.setStyleSheet("background-image: url(:/newPrefix/bulut.png);")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.pushButton_6 = QtWidgets.QPushButton(Form)
        self.pushButton_6.setGeometry(QtCore.QRect(20, 590, 61, 61))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: rgb(2, 177, 253);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(2, 150, 253);\n"
"\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(1460, 490, 500, 400))
        self.label_6.setMinimumSize(QtCore.QSize(320, 220))
        self.label_6.setMaximumSize(QtCore.QSize(500, 400))
        self.label_6.setStyleSheet("background-image: url(:/newPrefix/bulut.png);")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.pushButton_7 = QtWidgets.QPushButton(Form)
        self.pushButton_7.setGeometry(QtCore.QRect(170, 700, 51, 61))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color:#ff8bf0;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #ffb2f8;\n"
"\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Form)
        self.pushButton_8.setGeometry(QtCore.QRect(310, 660, 61, 61))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #415aff;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #6978ff;\n"
"\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Form)
        self.pushButton_9.setGeometry(QtCore.QRect(250, 720, 61, 61))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #ffb217;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #ffd735;\n"
"\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Form)
        self.pushButton_10.setGeometry(QtCore.QRect(280, 580, 51, 61))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_10.setFont(font)
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #aa7725;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#aa9341;\n"
"\n"
"}")
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(Form)
        self.pushButton_11.setGeometry(QtCore.QRect(70, 530, 61, 61))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_11.setFont(font)
        self.pushButton_11.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #ff115c;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #ff628c;\n"
"\n"
"}")
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(Form)
        self.pushButton_12.setGeometry(QtCore.QRect(140, 500, 71, 71))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_12.setFont(font)
        self.pushButton_12.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: rgb(2, 177, 253);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(2, 150, 253);\n"
"\n"
"}")
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(Form)
        self.pushButton_13.setGeometry(QtCore.QRect(20, 690, 61, 61))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color:#ff8bf0;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #ffb2f8;\n"
"\n"
"}")
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(Form)
        self.pushButton_14.setGeometry(QtCore.QRect(100, 730, 51, 51))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #aa7725;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#aa9341;\n"
"\n"
"}")
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(Form)
        self.pushButton_15.setGeometry(QtCore.QRect(220, 540, 61, 61))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #415aff;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #6978ff;\n"
"\n"
"}")
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(Form)
        self.pushButton_16.setGeometry(QtCore.QRect(120, 610, 61, 71))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_16.setFont(font)
        self.pushButton_16.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #ffb217;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #ffd735;\n"
"\n"
"}")
        self.pushButton_16.setObjectName("pushButton_16")
        self.pushButton_17 = QtWidgets.QPushButton(Form)
        self.pushButton_17.setGeometry(QtCore.QRect(220, 630, 51, 71))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #ff115c;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #ff628c;\n"
"\n"
"}")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(Form)
        self.pushButton_18.setGeometry(QtCore.QRect(250, 940, 71, 71))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: rgb(2, 177, 253);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(2, 150, 253);\n"
"\n"
"}")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(Form)
        self.pushButton_19.setGeometry(QtCore.QRect(410, 1000, 71, 71))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: rgb(2, 177, 253);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(2, 150, 253);\n"
"\n"
"}")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(Form)
        self.pushButton_20.setGeometry(QtCore.QRect(270, 870, 71, 61))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #ffb217;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #ffd735;\n"
"\n"
"}")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(Form)
        self.pushButton_21.setGeometry(QtCore.QRect(500, 1000, 61, 61))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #ffb217;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #ffd735;\n"
"\n"
"}")
        self.pushButton_21.setObjectName("pushButton_21")
        self.pushButton_22 = QtWidgets.QPushButton(Form)
        self.pushButton_22.setGeometry(QtCore.QRect(570, 960, 61, 61))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #ff115c;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #ff628c;\n"
"\n"
"}")
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(Form)
        self.pushButton_23.setGeometry(QtCore.QRect(360, 930, 61, 81))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #ff115c;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #ff628c;\n"
"\n"
"}")
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(Form)
        self.pushButton_24.setGeometry(QtCore.QRect(310, 1010, 61, 71))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color:#ff8bf0;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #ffb2f8;\n"
"\n"
"}")
        self.pushButton_24.setObjectName("pushButton_24")
        self.pushButton_25 = QtWidgets.QPushButton(Form)
        self.pushButton_25.setGeometry(QtCore.QRect(520, 900, 61, 71))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color:#ff8bf0;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #ffb2f8;\n"
"\n"
"}")
        self.pushButton_25.setObjectName("pushButton_25")
        self.pushButton_26 = QtWidgets.QPushButton(Form)
        self.pushButton_26.setGeometry(QtCore.QRect(450, 920, 51, 61))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_26.setFont(font)
        self.pushButton_26.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #aa7725;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#aa9341;\n"
"\n"
"}")
        self.pushButton_26.setObjectName("pushButton_26")
        self.pushButton_27 = QtWidgets.QPushButton(Form)
        self.pushButton_27.setGeometry(QtCore.QRect(420, 830, 51, 71))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_27.setFont(font)
        self.pushButton_27.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #aa7725;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#aa9341;\n"
"\n"
"}")
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(Form)
        self.pushButton_28.setGeometry(QtCore.QRect(490, 820, 61, 81))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_28.setFont(font)
        self.pushButton_28.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #415aff;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #6978ff;\n"
"\n"
"}")
        self.pushButton_28.setObjectName("pushButton_28")
        self.pushButton_29 = QtWidgets.QPushButton(Form)
        self.pushButton_29.setGeometry(QtCore.QRect(350, 830, 61, 81))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_29.setFont(font)
        self.pushButton_29.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #415aff;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #6978ff;\n"
"\n"
"}")
        self.pushButton_29.setObjectName("pushButton_29")
        self.pushButton_30 = QtWidgets.QPushButton(Form)
        self.pushButton_30.setGeometry(QtCore.QRect(1080, 940, 51, 61))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_30.setFont(font)
        self.pushButton_30.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #aa7725;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#aa9341;\n"
"\n"
"}")
        self.pushButton_30.setObjectName("pushButton_30")
        self.pushButton_31 = QtWidgets.QPushButton(Form)
        self.pushButton_31.setGeometry(QtCore.QRect(780, 1000, 51, 61))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_31.setFont(font)
        self.pushButton_31.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #aa7725;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#aa9341;\n"
"\n"
"}")
        self.pushButton_31.setObjectName("pushButton_31")
        self.pushButton_32 = QtWidgets.QPushButton(Form)
        self.pushButton_32.setGeometry(QtCore.QRect(850, 1000, 51, 71))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_32.setFont(font)
        self.pushButton_32.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color:#ff8bf0;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #ffb2f8;\n"
"\n"
"}")
        self.pushButton_32.setObjectName("pushButton_32")
        self.pushButton_33 = QtWidgets.QPushButton(Form)
        self.pushButton_33.setGeometry(QtCore.QRect(1000, 930, 51, 61))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_33.setFont(font)
        self.pushButton_33.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color:#ff8bf0;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #ffb2f8;\n"
"\n"
"}")
        self.pushButton_33.setObjectName("pushButton_33")
        self.pushButton_34 = QtWidgets.QPushButton(Form)
        self.pushButton_34.setGeometry(QtCore.QRect(980, 850, 61, 61))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_34.setFont(font)
        self.pushButton_34.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #ffb217;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #ffd735;\n"
"\n"
"}")
        self.pushButton_34.setObjectName("pushButton_34")
        self.pushButton_35 = QtWidgets.QPushButton(Form)
        self.pushButton_35.setGeometry(QtCore.QRect(1020, 1010, 61, 61))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_35.setFont(font)
        self.pushButton_35.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #ffb217;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #ffd735;\n"
"\n"
"}")
        self.pushButton_35.setObjectName("pushButton_35")
        self.pushButton_36 = QtWidgets.QPushButton(Form)
        self.pushButton_36.setGeometry(QtCore.QRect(720, 950, 61, 71))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_36.setFont(font)
        self.pushButton_36.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #ff115c;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #ff628c;\n"
"\n"
"}")
        self.pushButton_36.setObjectName("pushButton_36")
        self.pushButton_37 = QtWidgets.QPushButton(Form)
        self.pushButton_37.setGeometry(QtCore.QRect(920, 920, 51, 71))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_37.setFont(font)
        self.pushButton_37.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #ff115c;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #ff628c;\n"
"\n"
"}")
        self.pushButton_37.setObjectName("pushButton_37")
        self.pushButton_38 = QtWidgets.QPushButton(Form)
        self.pushButton_38.setGeometry(QtCore.QRect(870, 840, 71, 71))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_38.setFont(font)
        self.pushButton_38.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: rgb(2, 177, 253);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(2, 150, 253);\n"
"\n"
"}")
        self.pushButton_38.setObjectName("pushButton_38")
        self.pushButton_39 = QtWidgets.QPushButton(Form)
        self.pushButton_39.setGeometry(QtCore.QRect(770, 870, 51, 71))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_39.setFont(font)
        self.pushButton_39.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: rgb(2, 177, 253);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(2, 150, 253);\n"
"\n"
"}")
        self.pushButton_39.setObjectName("pushButton_39")
        self.pushButton_40 = QtWidgets.QPushButton(Form)
        self.pushButton_40.setGeometry(QtCore.QRect(930, 1000, 51, 71))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_40.setFont(font)
        self.pushButton_40.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #415aff;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #6978ff;\n"
"\n"
"}")
        self.pushButton_40.setObjectName("pushButton_40")
        self.pushButton_41 = QtWidgets.QPushButton(Form)
        self.pushButton_41.setGeometry(QtCore.QRect(830, 930, 51, 61))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_41.setFont(font)
        self.pushButton_41.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #415aff;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #6978ff;\n"
"\n"
"}")
        self.pushButton_41.setObjectName("pushButton_41")
        self.pushButton_42 = QtWidgets.QPushButton(Form)
        self.pushButton_42.setGeometry(QtCore.QRect(1310, 870, 61, 61))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_42.setFont(font)
        self.pushButton_42.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #ffb217;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #ffd735;\n"
"\n"
"}")
        self.pushButton_42.setObjectName("pushButton_42")
        self.pushButton_43 = QtWidgets.QPushButton(Form)
        self.pushButton_43.setGeometry(QtCore.QRect(1500, 840, 61, 61))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_43.setFont(font)
        self.pushButton_43.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #ffb217;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #ffd735;\n"
"\n"
"}")
        self.pushButton_43.setObjectName("pushButton_43")
        self.pushButton_44 = QtWidgets.QPushButton(Form)
        self.pushButton_44.setGeometry(QtCore.QRect(1230, 840, 71, 81))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_44.setFont(font)
        self.pushButton_44.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #aa7725;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#aa9341;\n"
"\n"
"}")
        self.pushButton_44.setObjectName("pushButton_44")
        self.pushButton_45 = QtWidgets.QPushButton(Form)
        self.pushButton_45.setGeometry(QtCore.QRect(1520, 920, 61, 81))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_45.setFont(font)
        self.pushButton_45.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #aa7725;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#aa9341;\n"
"\n"
"}")
        self.pushButton_45.setObjectName("pushButton_45")
        self.pushButton_46 = QtWidgets.QPushButton(Form)
        self.pushButton_46.setGeometry(QtCore.QRect(1270, 1000, 61, 71))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_46.setFont(font)
        self.pushButton_46.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #ff115c;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #ff628c;\n"
"\n"
"}")
        self.pushButton_46.setObjectName("pushButton_46")
        self.pushButton_47 = QtWidgets.QPushButton(Form)
        self.pushButton_47.setGeometry(QtCore.QRect(1460, 980, 51, 91))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_47.setFont(font)
        self.pushButton_47.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #ff115c;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #ff628c;\n"
"\n"
"}")
        self.pushButton_47.setObjectName("pushButton_47")
        self.pushButton_48 = QtWidgets.QPushButton(Form)
        self.pushButton_48.setGeometry(QtCore.QRect(1360, 930, 61, 71))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_48.setFont(font)
        self.pushButton_48.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color:#ff8bf0;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #ffb2f8;\n"
"\n"
"}")
        self.pushButton_48.setObjectName("pushButton_48")
        self.pushButton_49 = QtWidgets.QPushButton(Form)
        self.pushButton_49.setGeometry(QtCore.QRect(1410, 810, 51, 71))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_49.setFont(font)
        self.pushButton_49.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color:#ff8bf0;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #ffb2f8;\n"
"\n"
"}")
        self.pushButton_49.setObjectName("pushButton_49")
        self.pushButton_50 = QtWidgets.QPushButton(Form)
        self.pushButton_50.setGeometry(QtCore.QRect(1210, 940, 71, 71))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_50.setFont(font)
        self.pushButton_50.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #415aff;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #6978ff;\n"
"\n"
"}")
        self.pushButton_50.setObjectName("pushButton_50")
        self.pushButton_51 = QtWidgets.QPushButton(Form)
        self.pushButton_51.setGeometry(QtCore.QRect(1370, 1010, 51, 61))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_51.setFont(font)
        self.pushButton_51.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #415aff;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #6978ff;\n"
"\n"
"}")
        self.pushButton_51.setObjectName("pushButton_51")
        self.pushButton_52 = QtWidgets.QPushButton(Form)
        self.pushButton_52.setGeometry(QtCore.QRect(1320, 790, 71, 71))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_52.setFont(font)
        self.pushButton_52.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: rgb(2, 177, 253);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(2, 150, 253);\n"
"\n"
"}")
        self.pushButton_52.setObjectName("pushButton_52")
        self.pushButton_53 = QtWidgets.QPushButton(Form)
        self.pushButton_53.setGeometry(QtCore.QRect(1430, 890, 71, 71))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_53.setFont(font)
        self.pushButton_53.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: rgb(2, 177, 253);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(2, 150, 253);\n"
"\n"
"}")
        self.pushButton_53.setObjectName("pushButton_53")
        self.pushButton_54 = QtWidgets.QPushButton(Form)
        self.pushButton_54.setGeometry(QtCore.QRect(1750, 660, 71, 91))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_54.setFont(font)
        self.pushButton_54.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #ffb217;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #ffd735;\n"
"\n"
"}")
        self.pushButton_54.setObjectName("pushButton_54")
        self.pushButton_55 = QtWidgets.QPushButton(Form)
        self.pushButton_55.setGeometry(QtCore.QRect(1750, 580, 61, 61))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_55.setFont(font)
        self.pushButton_55.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #ffb217;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #ffd735;\n"
"\n"
"}")
        self.pushButton_55.setObjectName("pushButton_55")
        self.pushButton_56 = QtWidgets.QPushButton(Form)
        self.pushButton_56.setGeometry(QtCore.QRect(1800, 770, 61, 71))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_56.setFont(font)
        self.pushButton_56.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color:#ff8bf0;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #ffb2f8;\n"
"\n"
"}")
        self.pushButton_56.setObjectName("pushButton_56")
        self.pushButton_57 = QtWidgets.QPushButton(Form)
        self.pushButton_57.setGeometry(QtCore.QRect(1620, 780, 61, 71))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_57.setFont(font)
        self.pushButton_57.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color:#ff8bf0;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #ffb2f8;\n"
"\n"
"}")
        self.pushButton_57.setObjectName("pushButton_57")
        self.pushButton_58 = QtWidgets.QPushButton(Form)
        self.pushButton_58.setGeometry(QtCore.QRect(1630, 590, 61, 81))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_58.setFont(font)
        self.pushButton_58.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #aa7725;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#aa9341;\n"
"\n"
"}")
        self.pushButton_58.setObjectName("pushButton_58")
        self.pushButton_59 = QtWidgets.QPushButton(Form)
        self.pushButton_59.setGeometry(QtCore.QRect(1860, 710, 61, 81))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_59.setFont(font)
        self.pushButton_59.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #aa7725;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:#aa9341;\n"
"\n"
"}")
        self.pushButton_59.setObjectName("pushButton_59")
        self.pushButton_60 = QtWidgets.QPushButton(Form)
        self.pushButton_60.setGeometry(QtCore.QRect(1560, 670, 61, 91))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_60.setFont(font)
        self.pushButton_60.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #ff115c;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #ff628c;\n"
"\n"
"}")
        self.pushButton_60.setObjectName("pushButton_60")
        self.pushButton_61 = QtWidgets.QPushButton(Form)
        self.pushButton_61.setGeometry(QtCore.QRect(1720, 770, 51, 91))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_61.setFont(font)
        self.pushButton_61.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #ff115c;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #ff628c;\n"
"\n"
"}")
        self.pushButton_61.setObjectName("pushButton_61")
        self.pushButton_62 = QtWidgets.QPushButton(Form)
        self.pushButton_62.setGeometry(QtCore.QRect(1840, 620, 71, 71))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_62.setFont(font)
        self.pushButton_62.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #415aff;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #6978ff;\n"
"\n"
"}")
        self.pushButton_62.setObjectName("pushButton_62")
        self.pushButton_63 = QtWidgets.QPushButton(Form)
        self.pushButton_63.setGeometry(QtCore.QRect(1650, 680, 71, 91))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_63.setFont(font)
        self.pushButton_63.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"background-color: #415aff;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #6978ff;\n"
"\n"
"}")
        self.pushButton_63.setObjectName("pushButton_63")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(460, 220, 941, 471))
        self.label_7.setObjectName("label_7")
        self.pushButton_64 = QtWidgets.QPushButton(Form)
        self.pushButton_64.setGeometry(QtCore.QRect(200, 280, 211, 141))
        self.pushButton_64.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"    background-image: url(:/newPrefix/sil.png) ;\n"
"background-repeat: no-repeat;\n"
"background-color: transparent;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-image: url(:/newPrefix/sil_hover.png);\n"
"background-repeat: no-repeat;\n"
"background-color: transparent;\n"
"\n"
"\n"
"}")
        self.pushButton_64.setText("")
        self.pushButton_64.setObjectName("pushButton_64")
        self.pushButton_65 = QtWidgets.QPushButton(Form)
        self.pushButton_65.setGeometry(QtCore.QRect(1820, 10, 101, 91))
        self.pushButton_65.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"    background-image: url(:/newPrefix/cikis_normal.png) ;\n"
"background-repeat: no-repeat;\n"
"background-color: transparent;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-image: url(:/newPrefix/cikis_hover.png);\n"
"background-repeat: no-repeat;\n"
"background-color: transparent;\n"
"\n"
"\n"
"}")
        self.pushButton_65.setText("")
        self.pushButton_65.setObjectName("pushButton_65")
        self.pushButton_67 = QtWidgets.QPushButton(Form)
        self.pushButton_67.setGeometry(QtCore.QRect(20, 150, 201, 191))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_67.setFont(font)
        self.pushButton_67.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"    background-image: url(:/newPrefix/palet1.png) ;\n"
"background-repeat: no-repeat;\n"
"background-color: transparent;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-image: url(:/newPrefix/palet2.png);\n"
"background-repeat: no-repeat;\n"
"background-color: transparent;}")
        self.pushButton_67.setText("")
        self.pushButton_67.setObjectName("pushButton_67")
        self.pushButton_71 = QtWidgets.QPushButton(Form)
        self.pushButton_71.setGeometry(QtCore.QRect(820, 660, 261, 61))
        font = QtGui.QFont()
        font.setFamily("TTKB Dik Temel Abece")
        font.setPointSize(35)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.pushButton_71.setFont(font)
        self.pushButton_71.setStyleSheet("QPushButton{\n"
"\n"
"border-radius:20px;\n"
"background-color: #dedede;\n"
"}\n"
"QPushButton:hover{\n"
"background-color: #959595;\n"
"\n"
"}")
        self.pushButton_71.setText("")
        self.pushButton_71.setObjectName("pushButton_71")
        self.pushButton_66 = QtWidgets.QPushButton(Form)
        self.pushButton_66.setGeometry(QtCore.QRect(1310, 660, 101, 111))
        self.pushButton_66.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"    background-image: url(:/newPrefix/soru1.png) ;\n"
"background-repeat: no-repeat;\n"
"background-color: transparent;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-image: url(:/newPrefix/soru2.png);\n"
"background-repeat: no-repeat;\n"
"background-color: transparent;\n"
"\n"
"\n"
"}")
        self.pushButton_66.setText("")
        self.pushButton_66.setObjectName("pushButton_66")
        self.pushButton_68 = QtWidgets.QPushButton(Form)
        self.pushButton_68.setGeometry(QtCore.QRect(1190, 660, 101, 111))
        self.pushButton_68.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"    background-image: url(:/newPrefix/nokta1.png) ;\n"
"background-repeat: no-repeat;\n"
"background-color: transparent;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-image: url(:/newPrefix/nokta2.png);\n"
"background-repeat: no-repeat;\n"
"background-color: transparent;\n"
"\n"
"\n"
"}")
        self.pushButton_68.setText("")
        self.pushButton_68.setObjectName("pushButton_68")
        self.pushButton_69 = QtWidgets.QPushButton(Form)
        self.pushButton_69.setGeometry(QtCore.QRect(1120, 650, 101, 131))
        self.pushButton_69.setStyleSheet("QPushButton{\n"
"border-radius:20px;\n"
"    background-image: url(:/newPrefix/unlem1.png) ;\n"
"background-repeat: no-repeat;\n"
"background-color: transparent;\n"
"\n"
"}\n"
"QPushButton:hover{\n"
"    background-image: url(:/newPrefix/unlem2.png);\n"
"background-repeat: no-repeat;\n"
"background-color: transparent;\n"
"\n"
"\n"
"}")
        self.pushButton_69.setText("")
        self.pushButton_69.setObjectName("pushButton_69")
        self.pushButton_70 = QtWidgets.QPushButton(Form)
        self.pushButton_70.setGeometry(QtCore.QRect(1800, 1040, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_70.setFont(font)
        self.pushButton_70.setStyleSheet("QPushButton{\n"
"border-radius:10px;\n"
"background-color: rgb(2, 177, 253);\n"
"}\n"
"QPushButton:hover{\n"
"background-color: rgb(2, 150, 253);\n"
"\n"
"}")
        self.pushButton_70.setObjectName("pushButton_70")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton_6.setText(_translate("Form", "E"))
        self.pushButton_7.setText(_translate("Form", "L"))
        self.pushButton_8.setText(_translate("Form", "A"))
        self.pushButton_9.setText(_translate("Form", "K"))
        self.pushButton_10.setText(_translate("Form", "İ"))
        self.pushButton_11.setText(_translate("Form", "N"))
        self.pushButton_12.setText(_translate("Form", "e"))
        self.pushButton_13.setText(_translate("Form", "l"))
        self.pushButton_14.setText(_translate("Form", "i"))
        self.pushButton_15.setText(_translate("Form", "a"))
        self.pushButton_16.setText(_translate("Form", "k"))
        self.pushButton_17.setText(_translate("Form", "n"))
        self.pushButton_18.setText(_translate("Form", "O"))
        self.pushButton_19.setText(_translate("Form", "o"))
        self.pushButton_20.setText(_translate("Form", "m"))
        self.pushButton_21.setText(_translate("Form", "M"))
        self.pushButton_22.setText(_translate("Form", "U"))
        self.pushButton_23.setText(_translate("Form", "u"))
        self.pushButton_24.setText(_translate("Form", "T"))
        self.pushButton_25.setText(_translate("Form", "t"))
        self.pushButton_26.setText(_translate("Form", "Ü"))
        self.pushButton_27.setText(_translate("Form", "ü"))
        self.pushButton_28.setText(_translate("Form", "Y"))
        self.pushButton_29.setText(_translate("Form", "y"))
        self.pushButton_30.setText(_translate("Form", "Ö"))
        self.pushButton_31.setText(_translate("Form", "ö"))
        self.pushButton_32.setText(_translate("Form", "R"))
        self.pushButton_33.setText(_translate("Form", "r"))
        self.pushButton_34.setText(_translate("Form", "I"))
        self.pushButton_35.setText(_translate("Form", "ı"))
        self.pushButton_36.setText(_translate("Form", "D"))
        self.pushButton_37.setText(_translate("Form", "d"))
        self.pushButton_38.setText(_translate("Form", "S"))
        self.pushButton_39.setText(_translate("Form", "s"))
        self.pushButton_40.setText(_translate("Form", "B"))
        self.pushButton_41.setText(_translate("Form", "b"))
        self.pushButton_42.setText(_translate("Form", "Z"))
        self.pushButton_43.setText(_translate("Form", "z"))
        self.pushButton_44.setText(_translate("Form", "Ç"))
        self.pushButton_45.setText(_translate("Form", "ç"))
        self.pushButton_46.setText(_translate("Form", "G"))
        self.pushButton_47.setText(_translate("Form", "g"))
        self.pushButton_48.setText(_translate("Form", "Ş"))
        self.pushButton_49.setText(_translate("Form", "ş"))
        self.pushButton_50.setText(_translate("Form", "C"))
        self.pushButton_51.setText(_translate("Form", "c"))
        self.pushButton_52.setText(_translate("Form", "P"))
        self.pushButton_53.setText(_translate("Form", "p"))
        self.pushButton_54.setText(_translate("Form", "H"))
        self.pushButton_55.setText(_translate("Form", "h"))
        self.pushButton_56.setText(_translate("Form", "V"))
        self.pushButton_57.setText(_translate("Form", "v"))
        self.pushButton_58.setText(_translate("Form", "Ğ"))
        self.pushButton_59.setText(_translate("Form", "ğ"))
        self.pushButton_60.setText(_translate("Form", "F"))
        self.pushButton_61.setText(_translate("Form", "f"))
        self.pushButton_62.setText(_translate("Form", "J"))
        self.pushButton_63.setText(_translate("Form", "j"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p><br/></p></body></html>"))
        self.pushButton_70.setText(_translate("Form", "Hakkında"))
import ana_ekran_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
